CREATE TABLE Events (
	EventId INT NOT NULL, 
	Event VARCHAR(255) NOT NULL,
	PRIMARY KEY (EventId)
);

CREATE TABLE Songs (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL,
	EventID INT,
	SingerID INT,
	Lyrics TEXT,
	PRIMARY KEY (ID)
	CONSTRAINT EventSong FOREIGN KEY (EventID) 
	REFERENCES Events(EventId),
	CONSTRAINT SongOwner FOREIGN KEY (SingerID) 
	REFERENCES Singers(ID),
);

CREATE TABLE Relevence (
	ID INT NULL AUTO_INCREMENT,
	RateDate DATE,
	Value INT(1),
	UserId INT,
	PRIMARY KEY (ID)
	CONSTRAINT UserRate FOREIGN KEY (UserId) 
	REFERENCES Events(Id)
);

CREATE TABLE Singers(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255),
	PRIMARY KEY (ID)
);


CREATE TABLE Users(
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255),
	Birthday DATE,
);

CREATE TABLE Tempo(
	ID INT NOT NULL AUTO_INCREMENT,
	Value INT(1),
	SongID INT NOT NULL,
	CONSTRAINT SongTempo FOREIGN KEY (SongID)
	REFERENCES Songs(ID)
);
